resources:
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/kustomize/v1alpha6/without-lb?ref=release-0.7

patchesStrategicMerge:
- patch-ccm.yaml

patches:
- target:
    kind: KubeadmControlPlane
    name: \${CLUSTER_NAME}-control-plane
  path: patch-ccm-cloud-config.yaml
- target:
    kind: OpenStackMachineTemplate
  path: patch-security-group.yaml
