- op: add
  path: /spec/kubeadmConfigSpec/files/-
  value:
    content: ${OPENSTACK_CLOUD_CACERT_B64}
    encoding: base64
    owner: root
    path: /etc/certs/cacert
    permissions: "0600"
- op: add
  path: /spec/kubeadmConfigSpec/files/-
  value:
    content: ${OPENSTACK_CLOUD_YAML_B64}
    encoding: base64
    owner: root
    path: /etc/openstack/clouds.yaml
    permissions: "0600"
