---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: ${CLUSTER_NAME}-crs
spec:
  clusterSelector:
    matchLabels:
      crs: "true"
  resources:
  - kind: Secret
    name: ${CLUSTER_NAME}-crs
  strategy: Reconcile
