resources:
- ../cluster
- crs.yaml

patchesStrategicMerge:
- patch-cluster.yaml

secretGenerator:
- name: ${CLUSTER_NAME}-crs
  files:
  - cluster-resources.yaml
  type: addons.cluster.x-k8s.io/resource-set

generatorOptions:
  disableNameSuffixHash: true
