---
- hosts: localhost
  gather_facts: false
  vars_files:
  - terraform_vars.yml

  tasks:
  - name: Terraform deploy
    community.general.terraform:
      project_path: "../terraform"
      state: present
      variables: "{{ terraform_vars }}"
    register: terraform

  - name: Extract bastion public ip
    ansible.builtin.set_fact:
      bastion_public_ip: "{{ terraform.outputs.bastion.value.public_ip }}"

  - name: Print bastion public ip
    ansible.builtin.debug:
      msg: "Bastion IP: {{ bastion_public_ip }}"

  - name: Add bastion host
    ansible.builtin.add_host:
      name: bastion
      ansible_host: "{{ bastion_public_ip }}"
      ansible_user: "{{ ssh_user }}"
      # Disable host key checking
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

      internal_ip: "{{ terraform.outputs.bastion.value.private_ip }}"

  - name: Add OpenStack hosts
    ansible.builtin.add_host:
      name: "{{ item.name }}"
      groups:
      - openstack
      ansible_host: "{{ item.private_ip }}"
      ansible_user: "{{ ssh_user }}"
      # Use bastion as jump host, disabling host key checking everywhere
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p {{ ssh_user }}@{{ bastion_public_ip }}\""

    loop: "{{ terraform.outputs.hosts.value }}"

- hosts: bastion openstack
  become: yes
  roles:
  - ssh_keys
  - hosts

- hosts: bastion openstack
  tasks:
  - name: Generate keypair
    community.crypto.openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
    register: ssh_keypair

  - name: Store public key
    ansible.builtin.set_fact:
      public_key: "{{ ssh_keypair.public_key }}"

- hosts: openstack
  tasks:
    - name: Set authorized key
      ansible.posix.authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ hostvars[item]['public_key'] }}"
      with_items: "{{ groups['all'] }}"

- hosts: openstack
  gather_facts: no
  tasks:
  - name: Get all host keys
    ansible.builtin.command:
      cmd: "ssh-keyscan -t ecdsa {{ hostvars[inventory_hostname].ansible_host|default(inventory_hostname) }}"
    # we run this on the bastion since localhost won't have access to the other hosts until wireguard is up
    delegate_to: "bastion"
    register: "host_keys"
    changed_when: false

  - name: Ensure we found SSH keys
    ansible.builtin.assert:
      that: host_keys.stdout
      msg: "We did not get SSH key for {{inventory_hostname}}"

- hosts: bastion openstack
  vars:
  - known_hosts: "~/.ssh/known_hosts"
  tasks:
  - name: Stat known_hosts file for existance
    ansible.builtin.stat:
      path: "{{ known_hosts }}"
    register: fstat

  - name: Create known_hosts file if non-existing
    ansible.builtin.copy:
      content: "\n"
      dest: "{{ known_hosts }}"
    when: "not fstat.stat.exists"
    changed_when: false

  - name: Configure known_hosts file
    ansible.builtin.blockinfile:
      dest: "{{known_hosts}}"
      marker: "# {mark} This part managed by Ansible"
      block: |
        {% for h in groups['openstack'] | sort if hostvars[h].host_keys is defined and hostvars[h].host_keys.stdout is defined  %}
        {%  if hostvars[h].ansible_port is defined %}
        {%   for key in hostvars[h].host_keys.stdout_lines %}
        {{ h }},{{ key.partition(" ")[0] }} {{ key.partition(" ")[2] }}
        {%   endfor %}
        {%  else %}
        {{ h }},{{ hostvars[h].host_keys.stdout }}
        {%  endif %}
        {% endfor %}

- hosts: bastion
  become: yes
  vars_files:
  - wireguard.yml
  vars:
    wireguard_addresses:
    # bastion gets the first IP in the wireguard subnet
    - "{{ wireguard_cidr | ansible.utils.nthhost(1) }}/32"
    wireguard_endpoint: "{{ ansible_host }}"
    wireguard_postup:
    - "echo 1 > /proc/sys/net/ipv4/ip_forward"
    # SNAT to the internal and provider networks
    - "iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source {{ internal_ip }}"
    - "iptables -t nat -A POSTROUTING -o provider0 -j SNAT --to-source {{ provider_cidr | ansible.utils.nthhost(1) }}"
    wireguard_unmanaged_peers: "{{ wireguard_users }}"
  roles:
  - githubixx.ansible_role_wireguard

  tasks:
  - name: Extract WireGuard public key
    ansible.builtin.shell:
      cmd: awk '/^PrivateKey\s*=\s*/ {print $3}' /etc/wireguard/wg0.conf | wg pubkey
    register: wg_pubkey

  - name: Store WireGuard public key
    ansible.builtin.set_fact:
      wg_public_key: "{{ wg_pubkey.stdout | trim }}"

## Write stub wireguard configs locally
- hosts: localhost
  gather_facts: false
  vars:
    bastion_public_key: "{{ hostvars['bastion']['wg_public_key'] }}"
    bastion_public_ip: "{{ hostvars['bastion']['ansible_host'] }}"
  vars_files:
  - wireguard.yml

  tasks:
  - name: Create wireguard configs directory
    ansible.builtin.file:
      path: "../wg"
      state: directory
      mode: "0750"
    register: wg_dir

  - name: Write wireguard configs
    ansible.builtin.template:
      src: "templates/wireguard/wg.conf.j2"
      dest: "{{ wg_dir.path }}/{{ item.key }}.conf"
    vars:
      user_wireguard_ip: "{{ item.value.allowed_ips }}"
    loop: "{{ wireguard_users | dict2items }}"

## Configure provider0 interface on all hosts
- hosts: bastion openstack
  become: true
  tasks:
  - name: Write provider netplan
    ansible.builtin.template:
      src: "templates/netplan/60-provider.yaml.j2"
      dest: "/etc/netplan/60-provider.yaml"
    vars:
      # TODO: Ideally we want a loop here so we can handle an arbitrary number
      # of hosts. This limits us to a bastion and two hosts.
      configs:
        bastion:
          local_ip: "{{ hostvars['bastion']['internal_ip'] }}"
          remote_ips:
          - "{{ hostvars['host-00']['ansible_host'] }}"
          - "{{ hostvars['host-01']['ansible_host'] }}"
          tunnel_ip: "{{ provider_cidr | ansible.utils.nthhost(1) }}/{{ provider_cidr | ansible.utils.ipaddr('prefix') }}"
        host-00:
          local_ip: "{{ hostvars['host-00']['ansible_host'] }}"
          remote_ips:
          - "{{ hostvars['bastion']['internal_ip'] }}"
          - "{{ hostvars['host-01']['ansible_host'] }}"
          tunnel_ip: "{{ provider_cidr | ansible.utils.nthhost(2) }}/{{ provider_cidr | ansible.utils.ipaddr('prefix') }}"
        host-01:
          local_ip: "{{ hostvars['host-01']['ansible_host'] }}"
          remote_ips:
          - "{{ hostvars['bastion']['internal_ip'] }}"
          - "{{ hostvars['host-00']['ansible_host'] }}"
          tunnel_ip: "{{ provider_cidr | ansible.utils.nthhost(3) }}/{{ provider_cidr | ansible.utils.ipaddr('prefix') }}"
  - name: Apply provider netplan
    ansible.builtin.shell:
      cmd: netplan apply

- hosts: bastion
  become: yes
  tasks:
  - name: Configure NAT for provider network CIDR
    ansible.builtin.shell: |
      if ! iptables -t nat -L POSTROUTING | grep {{ provider_cidr }}; then
          iptables -t nat -A POSTROUTING -s {{ provider_cidr }} -o eth0 -j MASQUERADE
      fi

- hosts: bastion openstack
  become: true
  tasks:
  - name: Configure forwarding entries for all nodes, avoiding multicast
    ansible.builtin.shell: |
      additional_ips=({{ configs[inventory_hostname]|join(" ") }})
      for additional_ip in "${additional_ips[@]}"; do
          # This is idempotent
          bridge fdb append to 00:00:00:00:00:00 dst ${additional_ip} dev provider0
      done
    args:
      executable: /bin/bash
    vars:
      # TODO: We can do this better, but how?
      configs:
        bastion:
          - "{{ provider_cidr | ansible.utils.nthhost(2) }}"
          - "{{ provider_cidr | ansible.utils.nthhost(3) }}"
        host-00:
          - "{{ provider_cidr | ansible.utils.nthhost(1) }}"
          - "{{ provider_cidr | ansible.utils.nthhost(3) }}"
        host-01:
          - "{{ provider_cidr | ansible.utils.nthhost(1) }}"
          - "{{ provider_cidr | ansible.utils.nthhost(2) }}"

- hosts: openstack
  become: true
  vars:
    nova_disk: /dev/disk/azure/scsi1/lun10
    cinder_disk: /dev/disk/azure/scsi1/lun11
    fstype: ext4
  tasks:
  - name: Format nova disk
    community.general.filesystem:
      dev: "{{ nova_disk }}"
      fstype: "{{ fstype }}"

  - name: Create /var/lib/nova directory
    ansible.builtin.file:
      path: "/var/lib/nova"
      state: directory
      mode: "0750"

  - name: Mount /var/lib/nova
    ansible.posix.mount:
      path: "/var/lib/nova"
      src: "{{ nova_disk }}"
      fstype: "{{ fstype }}"
      state: mounted

  - name: Check for cinder disk
    ansible.builtin.stat:
      path: "{{ cinder_disk }}"
    register: cinder_check

  - name: Create a volume group for cinder
    community.general.lvg:
      vg: cinder-volumes
      pvs: "{{ cinder_disk }}"
    when: cinder_check.stat.exists
