apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: kube-system
stringData:
  cloud.conf: |
    [Global]
    use-clouds=true
    clouds-file=/etc/openstack/clouds.yaml
    cloud=${OPENSTACK_CLOUD}
